### ISSUE TITLE
Adding keywords to places-scope

### ISSUE THREAD

**Issue by bartoszkosiorek** [labsin/places-scope#2]
It will be great to integrate keywords into this scope.
It will allows to highly integrate with "NearBy" scope aggregator.

I would recommend to use following keywords: "nearby, poi, drink, food, business"
More information is available at:
https://developer.ubuntu.com/en/scopes/guides/scope-keywords/

**Comment by SeSamSeg** [comment]
I will look into this. Thanks
I haven't looked at my Ubuntu touch projects in a while as I don't own a device that runs it. I thought the desktop should come quicker.

Do you use this scope? I thought there where other scopes that did the same.

**Comment by bartoszkosiorek** [comment]
Hello Sam.

Unfortunately other "Google Places" scopes also do not contain keywords
(which were introduced lately).

If you don't have spare time to implement that I could provide
implementation proposal for your Scope, and test it on my BQ device.
What do you think about that idea?

Best Regards
Bartosz

2015-10-17 16:09 GMT+02:00 Sam Segers notifications@github.com:

**Comment by SeSamSeg** [comment]
I get an error on the click: "Unknown field in 'places/com.ubuntu.developer.labsin.places_places.ini': keywords" when I run the click validation.
Could you try the package?
https://drive.google.com/open?id=0B1euibKhpEeQQVhkREZfZkpaaWs

**Comment by bartoszkosiorek** [comment]
Thanks Sam.

Unfortunately I don't have access to that page.
Could you please create branch with your changes?
I will try to build it by ownselfs and check possible solutions.

The most experienced person in scopes is Kyle Nitzsche:
https://launchpad.net/~knitzsche
Maybe we could ask him for help?

**Comment by SeSamSeg** [comment]
I've pushed the changes. You still need an APP_KEY from google dashboard to use it.
The build system reads it from places.secret, it only has placeholders now.
You should now have access to the file now (it's the first time I used Google docs)

**Comment by bartoszkosiorek** [comment]
Awensome work! Thanks.

Do you know where I could translate strings for places-scope?

**Comment by SeSamSeg** [comment]
You can use standard translation software like poedit. The template is
po/places.pot
Poedit is in the standard repo. Here is a guide:
https://make.wordpress.org/polyglots/handbook/tools/poedit/  (you don't
need the mo file, only the po file)

You can purpose a merge request or just mail it.
